# .streamlit/secrets.toml

[firebaseConfig]
apiKey = "AIzaSyA7Eb_qs-BoNmNK3EUcRF-1ebO2nGvSYw4"
authDomain = "alphapredict-ai.firebaseapp.com"
databaseURL = "https://alphapredict-ai-default-rtdb.firebaseio.com"
projectId = "alphapredict-ai"
storageBucket = "alphapredict-ai.appspot.com"
messagingSenderId = "189247031279"
appId = "1:189247031279:web:073fa7e3edff200a42981a"
measurementId = "G-7WYBCQB3CK"
